fix pipeline rollback

diff --git a/.github/workflows/prod-pipeline.yml b/.github/workflows/prod-pipeline.yml
--- a/.github/workflows/prod-pipeline.yml
+++ b/.github/workflows/prod-pipeline.yml
@@ -96,27 +96,30 @@ jobs:
   run-integration-tests:
     runs-on: ubuntu-latest
     needs: build-push-deploy
+    outputs: 
+      integration_failed: ${{ steps.init.outputs.integration_failed }}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
       - name: Navigate to integration tests directory and 
         run: |
-            cd integration_tests && sudo npm install && sudo npx playwright install
+              cd integration_tests && sudo npm install && sudo npx playwright install
 
       - name: Run Tests
         run: |
-            cd integration_tests && sudo npx codeceptjs run --steps
+              cd integration_tests && sudo npx codeceptjs run --steps
         continue-on-error: true
 
       - name: Set output for integration failed
-        run: echo "integration_failed=$([[ $? -ne 0 ]] && echo true || echo false)" >> $GITHUB_ENV
+        run: |
+              echo "integration_failed=$([[ $? -ne 0 ]] && echo true || echo false)" >> $GITHUB_OUTPUT
 
 
   rollback-build-push-deploy:
     runs-on: ubuntu-latest
     needs: run-integration-tests
-    if: env.integration_failed == 'true'
+    if: needs.run-integration-tests.outputs.integration_failed == 'true'
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
